######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 8 19:56:17 2012
######################################################################

TEMPLATE = app
DESTDIR = dist
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += . src

# Input
HEADERS += src/VCardController.hpp src/VCardForm.hpp src/VCardModel.hpp
SOURCES += src/main.cpp \
           src/VCardController.cpp \
           src/VCardForm.cpp \
           src/VCardModel.cpp
